on: release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
      - uses: pascalgn/npm-publish-action@1.3.8
        name: Publish if version has been updated
        with:
          tag_name: 'v%s'
          tag_message: 'v%s'
          create_tag: 'true'
          commit_pattern: "release (\\S+)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
