on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node_version:
          - '12'
          - '14'
          - '16'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node_version}}
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
